---
- hosts: webservers
  become: yes
  become_method: sudo
  vars:
    worker_connections: 768
    worker_processes: 4
    max_open_files: 65506
  tasks:
    - name: install nginx
      apt: name=nginx update_cache=yes state=present

    - name: copy nginx config file
      template: src=/etc/ansible/deploy_nginx/nginx.conf.j2 dest=/etc/nginx/nginx.conf
      notify: restart nginx

    - name: copy index.html
      template:
        src: /etc/ansible/deploy_nginx/index.html.j2
        dest: /usr/share/nginx/www/index.html
        mode: 0644
      notify: restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
  
